FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements-backend.txt .
RUN pip install --index-url https://download.pytorch.org/whl/cpu torch==2.6.0+cpu && \
    pip install -r requirements-backend.txt

COPY app ./app
COPY resources ./resources

EXPOSE 8000

CMD ["gunicorn", "-w", "1", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:8000", "app.main:app"]
