[project]
name = "ds-rpc-01"
version = "0.1.0"
description = "Starter project for the RPC-01: Internal Chatbot with Role Based Access Control"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "streamlit>=1.38.0",
    "requests>=2.32.0",
    "python-dotenv>=1.0.0",
    "langchain-huggingface>=1.2.2",
    "sentence-transformers>=6.0.1",
    "langsmith>=0.3.0",
    "azure-core>=1.32.0",
    "azure-search-documents>=11.6.0",
]
